### ISSUE TITLE
Core vs Formio.js Question

### ISSUE THREAD

**Issue by aminmc** [formio/core#1]
@travist I presume this library is purely for rendering forms?   Can the template system still be used with this lib?

**Comment by travist** [comment]
Yes, this library is intended to serve as the "core" rendering system which includes the template system. Our goal is to then refactor the existing "formio.js" library to be called "@formio/forms" which will be the renderer library built on top of this "framework".  We have recognized that our renderer has become bloated and this is our approach to solve this problem. We will keep this library minimalistic and the renderer will extend it to introduce all the components you know today, but with a much more minimalistic interface as seen in the "components" folder of this library. Hope you agree with this approach.

**Comment by travist** [comment]
On a separate note. This library is actually intended to render anything. Some of the core components are HTML and HTML Container, which could technically render anything you like using JSON schemas.
