### ISSUE TITLE
[BUG] Unknown plugin option jsonLogic

### ISSUE THREAD

**Issue by cetsupport** [formio/core#6]
## Environment
Please provide as many details as you can:
Direct use the  formio/core render library in dist folder, found report error:
Unknown plugin option jsonLogic.

Then trying to build from source, get same error after invoke "npm install"

BTW, there no detail information about how to use the core library. like like to load plugin by usePlugin.

- Hosting type
  - [ ] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: N/A
- Frontend framework: N/A
- Browser: Chrome
- Browser version: 92.0.4515.107

## Steps to Reproduce
1. npm install
2. 
3. 

## Expected behavior
No error.

**Comment by cetsupport** [comment]
@travist I think this plugin should register under rules, is this understand correct? I guess that we should apply the same logic with "rules".

**Comment by Justman100** [comment]
@lane-formio

What about this? It's extremly important

**Comment by NexPlex** [comment]
I am having the same issue

**Comment by Justman100** [comment]
@brendanbond @AlexeyNikipelau

**Comment by lane-formio** [comment]
This is expected to be resolved in the next major release. We've seen the error but it hasn't blocked us from anything. 🤔

**Comment by lane-formio** [comment]
<div>Agent Jeriah Henley linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/48981">48981</a> for this issue.</div><br/>

**Comment by ZenMasterJacob20011** [comment]
Looks like this has been fixed in by these commits...
https://github.com/formio/core/commit/7018209ce0f78df7a20b6bb2329b86480ec6191d
https://github.com/formio/core/commit/8042210d39db250b5a668a9bb7c2d3bf03deb0fd
